apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-burn-app
  namespace: gpu-workload-app # ApplicationSet에 설정한 네임스페이스와 동일해야 함
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-burn
  template:
    metadata:
      labels:
        app: gpu-burn
    spec:
      containers:
        - name: cuda-container
          image: 'nvidia/cuda:12.2.0-base-ubuntu22.04'
          command:
            - /bin/sh
            - '-c'
          args:
            - nvidia-smi; while true; do sleep 30; done
          resources:
            limits:
              nvidia.com/gpu: '1'
            requests:
              nvidia.com/gpu: '1'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always