apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-burn-app
  namespace: gpu-workload-app # ApplicationSet에 설정한 네임스페이스와 동일해야 함
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-burn
  template:
    metadata:
      labels:
        app: gpu-burn
    spec:
      containers:
      - name: gpu-burn
        image: nvidia/samples:vectoradd-fortran # NVIDIA 공식 샘플
        command: ["/bin/sh", "-c"]
        args: ["/opt/nvidia/samples/vectorAdd_fortran; while true; do sleep 30; done"]
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
      restartPolicy: Always