server.port=8888
spring.application.name=demo
 
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=postgre  
spring.datasource.password=root 
spring.datasource.url=jdbc:postgresql://localhost:5432/demodb?currentSchema=public
#spring.datasource.url=jdbc:postgresql://postgresql:5432/demodb?currentSchema=public